# Generated by Django 3.2 on 2022-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='deals',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
